# Generated by Django 4.2.20 on 2025-05-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('website', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=40)),
                ('problem', models.TextField()),
                ('code', models.TextField()),
                ('runResult', models.CharField(max_length=40)),
                ('examples', models.JSONField()),
                ('ans', models.TextField()),
                ('messages', models.JSONField()),
            ],
        ),
    ]
